services:
  - type: web
    name: geo-presenze
    runtime: python
    rootDir: geopresenze
    buildCommand: pip install --use-deprecated=legacy-resolver -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.10"
    disk:
      name: faces-storage
      mountPath: /opt/render/project/src/geopresenze/static/faces
      sizeGB: 1
